
package com.greenfoxacademy.bankingbackofficebackendservice.soap;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-b01-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "string", targetNamespace = "http://schemas.microsoft.com/2003/10/Serialization/")
public class MNBArfolyamServiceSoapGetCurrentExchangeRatesStringFaultFaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private String faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public MNBArfolyamServiceSoapGetCurrentExchangeRatesStringFaultFaultMessage(String message, String faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public MNBArfolyamServiceSoapGetCurrentExchangeRatesStringFaultFaultMessage(String message, String faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: java.lang.String
     */
    public String getFaultInfo() {
        return faultInfo;
    }

}
