
package com.greenfoxacademy.bankingbackofficebackendservice.soap;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "MNBArfolyamServiceSoapImpl", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://www.mnb.hu/arfolyamok.asmx?WSDL")
public class MNBArfolyamServiceSoapImpl
    extends Service
{

    private final static URL MNBARFOLYAMSERVICESOAPIMPL_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.greenfoxacademy.bankingbackofficebackendservice.soap.MNBArfolyamServiceSoapImpl.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.greenfoxacademy.bankingbackofficebackendservice.soap.MNBArfolyamServiceSoapImpl.class.getResource(".");
            url = new URL(baseUrl, "http://www.mnb.hu/arfolyamok.asmx?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://www.mnb.hu/arfolyamok.asmx?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MNBARFOLYAMSERVICESOAPIMPL_WSDL_LOCATION = url;
    }

    public MNBArfolyamServiceSoapImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MNBArfolyamServiceSoapImpl() {
        super(MNBARFOLYAMSERVICESOAPIMPL_WSDL_LOCATION, new QName("http://tempuri.org/", "MNBArfolyamServiceSoapImpl"));
    }

    /**
     * 
     * @return
     *     returns MNBArfolyamServiceSoap
     */
    @WebEndpoint(name = "CustomBinding_MNBArfolyamServiceSoap")
    public MNBArfolyamServiceSoap getCustomBindingMNBArfolyamServiceSoap() {
        return super.getPort(new QName("http://tempuri.org/", "CustomBinding_MNBArfolyamServiceSoap"), MNBArfolyamServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MNBArfolyamServiceSoap
     */
    @WebEndpoint(name = "CustomBinding_MNBArfolyamServiceSoap")
    public MNBArfolyamServiceSoap getCustomBindingMNBArfolyamServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "CustomBinding_MNBArfolyamServiceSoap"), MNBArfolyamServiceSoap.class, features);
    }

}
