create table branch
(
    id      integer generated by default as identity,
    address varchar(255) not null,
    city    varchar(255) not null,
    zip     varchar(255) not null,
    primary key (id)
);
alter table branch
    add constraint UniqueCityAndAddress unique (city, address);
