create table client
(
    id         integer generated by default as identity,
    address    varchar(255) not null,
    birth_date DATE         not null,
    clientid   varchar(255) not null,
    email      varchar(255) not null,
    name       varchar(255) not null,
    phone      varchar(255) not null,
    pin        varchar(255) not null,
    primary key (id)
);
alter table client
    add constraint UniquePin unique (pin);
