create table account
(
    id             integer generated by default as identity,
    account_number varchar (255) not null,
    value          bigint not null,
    currency       varchar (255) not null,
    client_id      bigint not null,

    primary key (id),

    foreign key (client_id)
        references client(id)

)

