create table employee
(
    id        integer generated by default as identity,
    name      varchar(255) not null,
    branch_id integer      not null,
    primary key (id)
);

alter table employee
    add constraint FK_EMPLOYEE_BRANCH foreign key (branch_id) references branch;

insert into employee (name, branch_id)
values ('Lukács Benedek', 1),
       ('Szőke Patrik', 1),
       ('Biró András', 1),
       ('Gáspár Erika', 1),
       ('Jakab Anett', 1),
       ('Egyed Csilla', 1),
       ('Rácz Dalma', 1),
       ('László Béla', 2),
       ('Faragó Lajos', 2),
       ('Pásztor Laura', 2),
       ('Fülöp Dorka', 2),
       ('Barta Veronika', 3),
       ('Deák Tamara', 3),
       ('Szücs László', 3),
       ('Pintér Domonkos', 3),
       ('Bakos Pál', 3);

