create table transaction
(
    id                    integer generated by default as identity,
    source_account_number varchar(24) not null,
    target_account_number varchar(34) not null,
    source_currency        varchar(3) not null,
    target_currency        varchar(3) not null,
    date                   datetime ,
    amount                 double,
    exchange_rate          double,

    primary key (id)

)





